CREATE TABLE BOOKS
(
    ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    BOOK_TITLE VARCHAR(255) NOT NULL,
    BOOK_AUTHOR VARCHAR(255),
    ISBN VARCHAR(255),
    DESCR VARCHAR(255),
    IMAGE VARCHAR(255),
    PATH VARCHAR(255),
    LIKES INT(11),
    DISLIKES INT(11)
);